Added dependencies in pom.xml for neo4j's web console....
Added commented out code to unpack the zip/jar's to the WAR in tomcat to
resolve the ISSUE:
SEVERE: /webadmin/js/require.js
java.lang.IllegalStateException: zip file closed

Added serverWrapper bean config in appContext-Neo4j.xml to have a
Restful wrapper to enable/access the Web console for Neo4j web console.